### ISSUE TITLE
NoSuchMethodError when running project after direct download

### ISSUE THREAD

**Issue by pvb221** [DBCG/spark-cql-fhir#1]
Hello,

I was trying to run this project for some prototyping. I ran into the following exception when I submitted the JAR to Spark for local execution. It seems like the versions in the POM file are somehow incompatible

Caused by: java.lang.NoSuchMethodError: 'org.hl7.elm_modelinfo.r1.ModelInfo org.cqframework.cql.cql2elm.ModelInfoLoader.getModelInfo(org.hl7.elm.r1.VersionedIdentifier)'
	at org.opencds.cqf.cql.evaluator.cql2elm.model.CacheAwareModelManager.buildModel(CacheAwareModelManager.java:43)
	at org.opencds.cqf.cql.evaluator.cql2elm.model.CacheAwareModelManager.resolveModel(CacheAwareModelManager.java:82)
	at org.cqframework.cql.cql2elm.LibraryBuilder.loadModel(LibraryBuilder.java:168)
	at org.cqframework.cql.cql2elm.LibraryBuilder.getModel(LibraryBuilder.java:187)
	at org.cqframework.cql.cql2elm.LibraryBuilder.getSystemModel(LibraryBuilder.java:363)
	at org.cqframework.cql.cql2elm.LibraryBuilder.loadSystemLibrary(LibraryBuilder.java:384)
	at org.cqframework.cql.cql2elm.LibraryBuilder.beginTranslation(LibraryBuilder.java:520)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visitLibrary(Cql2ElmVisitor.java:385)
	at org.cqframework.cql.gen.cqlParser$LibraryContext.accept(cqlParser.java:341)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.cqframework.cql.cql2elm.Cql2ElmVisitor.visit(Cql2ElmVisitor.java:316)
	at org.cqframework.cql.cql2elm.CqlTranslator.translateToELM(CqlTranslator.java:601)
	at org.cqframework.cql.cql2elm.CqlTranslator.<init>(CqlTranslator.java:383)
	at org.cqframework.cql.cql2elm.CqlTranslator.fromStream(CqlTranslator.java:326)
	at org.cqframework.cql.cql2elm.LibraryManager.translateLibrary(LibraryManager.java:117)
	at org.cqframework.cql.cql2elm.LibraryManager.resolveLibrary(LibraryManager.java:92)
	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.translate(TranslatingLibraryLoader.java:141)
	at org.opencds.cqf.cql.evaluator.engine.execution.TranslatingLibraryLoader.load(TranslatingLibraryLoader.java:86)
	at org.opencds.cqf.cql.evaluator.engine.execution.PriorityLibraryLoader.lambda$load$0(PriorityLibraryLoader.java:20)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.opencds.cqf.cql.evaluator.engine.execution.PriorityLibraryLoader.load(PriorityLibraryLoader.java:20)
	at org.opencds.cqf.cql.engine.execution.CqlEngine.loadAndValidate(CqlEngine.java:248)
	at org.opencds.cqf.cql.engine.execution.CqlEngine.evaluate(CqlEngine.java:152)
	at org.opencds.cqf.cql.evaluator.CqlEvaluator.evaluate(CqlEvaluator.java:89)
	at org.opencds.cqf.cql.evaluator.CqlEvaluator.evaluate(CqlEvaluator.java:80)
	at org.opencds.cqf.cql.spark.sample.transform.EvaluatorMapPartitionsFunction.call(EvaluatorMapPartitionsFunction.java:134)
	at org.apache.spark.sql.Dataset.$anonfun$mapPartitions$1(Dataset.scala:2826)
	at org.apache.spark.sql.execution.MapPartitionsExec.$anonfun$doExecute$3(objects.scala:201)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by pvb221** [comment]
Was able to resolve by changing the version of the CQL Translator to 1.5.3
